Repository undp/design-system, pull requests merged in 2022-02, with the labels that each got.

#801 document-for-components-forms
  stories/Components/Forms/Checkbox/Checkbox.stories.mdx
  stories/Components/Forms/Dropdowns/CustomSelect/CustomSelect.stories.mdx
  stories/Components/Forms/Dropdowns/Multiselect/MultiSelect.stories.mdx
  stories/Components/Forms/InputFields/InputFields.stories.mdx
  stories/Components/Forms/Radio/Radio.stories.mdx
Labels: Conflicts

#868 und-1310 UAT Feedback - Template -10 - SDG page(English, Japanese, Ar…
  stories/Components/UIcomponents/Cards/StatsCards/stats-cards.scss
  stories/Molecules/Sdgmodal/sdgmodal.scss
  stories/Templates/Sdg/Sdg.stories.mdx
  stories/assets/js/sdg-modal.js
Labels: bug, WIP

#877 UNDP-1340-genric-sticky
  stories/Templates/GenericPage/GenericPage.jsx
  stories/Templates/GenericPage/generic-page.scss
  stories/Templates/PublicationPage/PublicationPage.jsx
  stories/assets/js/sticky.js
Labels: Good to merge

#885 SDG COLOR CHANGE
  stories/Molecules/Sdg/sdg.scss
  stories/Molecules/Sdgmodal/sdgmodal.scss
  stories/Templates/Sdg/Sdg.stories.mdx
  stories/assets/scss/_variables.scss
Labels: Good to merge
